### ISSUE TITLE
UX on iPad #3 - Observations

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftTermApp#126]
This is a follow up to #7 and #55 

General issues:

- [x] Landing page looks bad at startup, currently shows an empty Detail View, and even sessions is ugly.   Figure out a good idiom for the default page. See #131 
- [x] Buttons for actions like "Add Host", "Add Key" take a lot of space, and the layout is not optimal.  Put a max size, and when we have multiple, maybe use a different tool than a List
- [x]  Host listing, Key listing, Known Host listing look horrible as List items with a lot of space, perhaps we need cells and a different layout for them.
- [x] Empty pages (Hosts, Keys) probably could use a graphic/text explaining the purpose of a page.

**Comment by rcarmo** [comment]
Also, font sizes are a smidgeon small for the iPad by default.

**Comment by migueldeicaza** [comment]
@rcarmo I fixed the font sizes by default now, let me know if it works!
