### ISSUE TITLE
Starting a connection from Sessions navigates immediately back to Sessions

### ISSUE THREAD

**Issue by JosephHill** [migueldeicaza/SwiftTermApp#151]
After closing a connection in Sessions, I can start a new session from the list of Recent Sessions that is displayed when there are no active connections.  When I create the new connection, it navigates me to a terminal and then immediately navigates back to the Sessions screen so that I have to tap the session I just started to get back into the terminal.  It should just leave me on the terminal screen when it goes there the first time.

**Comment by migueldeicaza** [comment]
Duplicate #142
