### ISSUE TITLE
Return key does not work on Windows host

### ISSUE THREAD

**Issue by JosephHill** [migueldeicaza/SwiftTermApp#164]
From Instabug bug report 31:
The onscreen keyboard Return key does not work when connecting to an ssh server running on Windows.  

When testing on simulator, the Return key on the physical Mac keyboard works as expected.

**Comment by oleksis** [comment]
Thanks for responding the issue. Here attached the image. I’m testing with `CMD` and `PowerShell` getting the same results. 

![SwiftTerm](https://user-images.githubusercontent.com/44526468/163027964-4bd6aeea-27c0-4867-a85d-dc6211780229.jpg)

I’m using __oh-my-posh__ I will like support for Fonts  like [Nerd Font](https://ohmyposh.dev/docs/config-fonts)

**Comment by migueldeicaza** [comment]
This should be fixed on the next release
