### ISSUE TITLE
Today's iOS release, 1.3, cannot create new keys

### ISSUE THREAD

**Issue by kode54** [migueldeicaza/SwiftTermApp#175]
I just installed 1.3 on my iPhone SE 2, and cannot create either an Enclave key or a plaintext key. Either option appears to do nothing.

E: Scratch that, it appears that 1.3 is not displaying any keys that I previously created on my Mac mini, either.

**Comment by migueldeicaza** [comment]
I made a mistake while spicing up the UI, can you test the new version, it should include the fix (I also messed up Hosts in the same change, oops).

**Comment by kode54** [comment]
Ah, neat. Figured it was something to do with changing and accidentally breaking a listing control of some sort. I should follow the source updates too.
