### ISSUE TITLE
Resizing the app does not resize terminal sessions, and neither does closing the sidebar

### ISSUE THREAD

**Issue by kode54** [migueldeicaza/SwiftTermApp#181]
Not sure if this is applicable to rotation on iPads, or resizing the view in split views, as I haven't tested there yet. It does affect resizable windows on macOS on Apple Silicon, however. Resizing the window does not change the size of the underlying terminal session, so it remains fixed to the width it was created at. This includes if closing the sidebar, the terminal just slides over but doesn't get wider to fill the window.

**Comment by migueldeicaza** [comment]
I think I am going to use a different build for Mac computers, as the iOS emulation on M1 turns out has a bunch of other bugs I can't fix (like accelerators not working, crashes with some key combinations inside Apple's frameworks)
