### ISSUE TITLE
Enter/return key sends ^j instead of ^m (line feed instead of carriage return)

### ISSUE THREAD

**Issue by EmiliaBlasten** [migueldeicaza/SwiftTermApp#207]
Connecting to an Ubuntu server and using nano, emacs, etc. is difficult because the app sends ^j instead of ^m. For example to write
```
hello
world
```
in nano, I cannot type
```
hello[enter-key on the keyboard]world
```
but have to type
```
hello^mworld
```

Is there a setting which allows modifying these? I do not have this issue when using the ssh command in apps like ish or a-Shell.

**Comment by migueldeicaza** [comment]
Likely your terminal settings are wrong.  Check stty -a
